/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantasha;

import clases.Ciudad;
import clases.Validar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeString.trim;
import querys.Qcargo;
import querys.Qciudad;
import querys.Qproveedor;

/**
 *
 * @author Ariel
 */
public class ven_ciudad extends javax.swing.JFrame {

    Ciudad ci = new Ciudad();
    Qciudad qp = new Qciudad();
    Validar vali = new Validar();
    Qproveedor qprov = new Qproveedor();

    public ven_ciudad() {
        initComponents();
        this.setLocationRelativeTo(null);
        tbl_ciudad.setModel(qp.cargardatos());
        cmb_ciudad.setModel(cargarcmb_filtro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_cod_ciudad = new javax.swing.JLabel();
        lbl_nom_ciudad = new javax.swing.JLabel();
        txt_cod_ciudad = new javax.swing.JTextField();
        txt_nom_ciudad = new javax.swing.JTextField();
        btn_agregar_ciudad = new javax.swing.JButton();
        btn_modificar_ciudad = new javax.swing.JButton();
        btn_consultar_ciudad = new javax.swing.JButton();
        btn_eliminar_ciudad = new javax.swing.JButton();
        btn_salir_ciudad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ciudad = new javax.swing.JTable();
        cmb_ciudad = new javax.swing.JComboBox<>();
        txt_ciudad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        lbl_cod_ciudad.setText("codigo de la ciudad");

        lbl_nom_ciudad.setText("nombre de la ciudad");

        txt_cod_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_ciudadKeyTyped(evt);
            }
        });

        txt_nom_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nom_ciudadKeyTyped(evt);
            }
        });

        btn_agregar_ciudad.setText("agregar");
        btn_agregar_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar_ciudadMouseClicked(evt);
            }
        });

        btn_modificar_ciudad.setText("modificar");
        btn_modificar_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificar_ciudadMouseClicked(evt);
            }
        });

        btn_consultar_ciudad.setText("consultar");
        btn_consultar_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultar_ciudadMouseClicked(evt);
            }
        });

        btn_eliminar_ciudad.setText("eliminar");
        btn_eliminar_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminar_ciudadMouseClicked(evt);
            }
        });
        btn_eliminar_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_ciudadActionPerformed(evt);
            }
        });

        btn_salir_ciudad.setText("volver");
        btn_salir_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salir_ciudadMouseClicked(evt);
            }
        });

        tbl_ciudad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ciudadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ciudad);

        cmb_ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ciudadKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_agregar_ciudad)
                                .addGap(40, 40, 40)
                                .addComponent(btn_modificar_ciudad)
                                .addGap(37, 37, 37)
                                .addComponent(btn_consultar_ciudad))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_nom_ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(lbl_cod_ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_cod_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nom_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btn_eliminar_ciudad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(btn_salir_ciudad))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(cmb_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cod_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cod_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nom_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar_ciudad)
                    .addComponent(btn_modificar_ciudad)
                    .addComponent(btn_consultar_ciudad)
                    .addComponent(btn_eliminar_ciudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btn_salir_ciudad)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregar_ciudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar_ciudadMouseClicked
        ci.setCod_ciudad(trim(txt_cod_ciudad.getText()));
        ci.setNom_ciudad(trim(txt_nom_ciudad.getText()));

        if (trim(ci.getCod_ciudad()).equals("") || trim(ci.getNom_ciudad()).equals("")) {
            JOptionPane.showMessageDialog(null, "indique codigo no se puede agregar una ciudad sin codigo o sin nombre");

        } else {

            qp.agregarciudad(ci);

            actualizar();
            Limpiar();
        }

        Limpiar();
    
    }//GEN-LAST:event_btn_agregar_ciudadMouseClicked

    private void btn_modificar_ciudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificar_ciudadMouseClicked
       ci.setCod_ciudad(trim(txt_cod_ciudad.getText()));
         ci.setNom_ciudad(trim(txt_nom_ciudad.getText()));
        
        if (trim(ci.getCod_ciudad()).equals("") || trim(ci.getNom_ciudad()).equals("")) {
            JOptionPane.showMessageDialog(null, "indique codigo no se puede modificar una ciudad sin codigo o sin nombre");

        } else {

            qp.modificarciudad(ci);

            actualizar();
            Limpiar();
        }

        Limpiar();
    
                                    
    }//GEN-LAST:event_btn_modificar_ciudadMouseClicked

    private void btn_consultar_ciudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultar_ciudadMouseClicked
          ci.setCod_ciudad(trim(txt_cod_ciudad.getText()));  
        
        if(ci.getCod_ciudad().equals("")){
              JOptionPane.showMessageDialog(null, "indique codigo no se puede consultar una ciudad sin codigo");
        }else{
        
        qp.consultarciudad(ci);
           actualizar();
            Limpiar();
        }

        Limpiar();
    
        
         
    }//GEN-LAST:event_btn_consultar_ciudadMouseClicked

    private void btn_eliminar_ciudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminar_ciudadMouseClicked
      
         ci.setCod_ciudad(trim(txt_cod_ciudad.getText()));  
         if (txt_cod_ciudad.getText().equals("")) {
                 System.out.println("ingrese un codigo a eliminar");
         } else if (JOptionPane.showConfirmDialog(null, "Si elimina la ciudad se eliminaran los proveedores con esta ciudad  " + ci.getCod_ciudad(), "Eliminar ciudad",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {
            qprov.eliminarprovporciudad(ci);
             qp.eliminarciudad(ci);
            tbl_ciudad.removeAll();
            actualizar();
        }
          
       
    }//GEN-LAST:event_btn_eliminar_ciudadMouseClicked

    private void btn_salir_ciudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salir_ciudadMouseClicked
       ven_principal vp = new ven_principal();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salir_ciudadMouseClicked

    private void btn_eliminar_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_ciudadActionPerformed
             ci.setCod_ciudad(trim(txt_cod_ciudad.getText()));
          if  (ci.getCod_ciudad().equals("")){
              JOptionPane.showMessageDialog(null, "Seleccione o indique codigo del producto a eliminar");
              
          }else{
              if (JOptionPane.showConfirmDialog(null, "Desea eliminar la ciudad con codigo  " + ci.getCod_ciudad(), "Eliminar ciudad",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {
                qp.eliminarciudad(ci.getCod_ciudad());
                tbl_ciudad.removeAll();
                
                actualizar();
                Limpiar();
              }
               Limpiar();
          } 
    }//GEN-LAST:event_btn_eliminar_ciudadActionPerformed

    private void tbl_ciudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ciudadMouseClicked
       
        txt_cod_ciudad.setText(tbl_ciudad.getModel().getValueAt(tbl_ciudad.getSelectedRow(), 0).toString());
        txt_nom_ciudad.setText(tbl_ciudad.getModel().getValueAt(tbl_ciudad.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tbl_ciudadMouseClicked

    private void txt_cod_ciudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_ciudadKeyTyped
        vali.validarlargoalfa(evt, txt_cod_ciudad,10);
    }//GEN-LAST:event_txt_cod_ciudadKeyTyped

    private void txt_nom_ciudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nom_ciudadKeyTyped
       vali.validarlargoalfa(evt, txt_cod_ciudad,30);
    }//GEN-LAST:event_txt_nom_ciudadKeyTyped

    private void txt_ciudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ciudadKeyReleased
         String buscar = (String) cmb_ciudad.getSelectedItem();
       tbl_ciudad.setModel(qp.buscarDatos(txt_ciudad.getText(), buscar));
    }//GEN-LAST:event_txt_ciudadKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ven_ciudad.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ven_ciudad.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ven_ciudad.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ven_ciudad.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ven_ciudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_ciudad;
    private javax.swing.JButton btn_consultar_ciudad;
    private javax.swing.JButton btn_eliminar_ciudad;
    private javax.swing.JButton btn_modificar_ciudad;
    private javax.swing.JButton btn_salir_ciudad;
    private javax.swing.JComboBox<String> cmb_ciudad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cod_ciudad;
    private javax.swing.JLabel lbl_nom_ciudad;
    private javax.swing.JTable tbl_ciudad;
    private javax.swing.JTextField txt_ciudad;
    private javax.swing.JTextField txt_cod_ciudad;
    private javax.swing.JTextField txt_nom_ciudad;
    // End of variables declaration//GEN-END:variables
 public void Limpiar() {
        txt_cod_ciudad.setText("");
        txt_nom_ciudad.setText("");
        
    }

       public void actualizar(){
         DefaultTableModel modelo = new DefaultTableModel();
         modelo=qp.cargardatos();
         tbl_ciudad.setModel(modelo);
    }
    
    
      public DefaultComboBoxModel cargarcmb_filtro(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Codigo");
        modelo.addElement("Nombre");      
        return modelo;
    }
    


}
