/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantasha;

import clases.Producto;
import clases.Proveedores;
import clases.Validar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeString.trim;
import querys.Qproductos;
import querys.Qproveedor;

/**
 *
 * @author Ivan
 */
public class ven_proveedor extends javax.swing.JFrame {

    Qproveedor qp = new Qproveedor();
    Proveedores prov = new Proveedores();
    Validar vali = new Validar();
    
    public ven_proveedor() {
        initComponents();
         this.setLocationRelativeTo(null);
        tbl_proveedores.setModel(qp.cargardatos());
        cmb_proveedor.setModel(cargarcmb_filtro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_cod_prov = new javax.swing.JTextField();
        txt_cod_ciudad_prov = new javax.swing.JTextField();
        txt_nom_prov = new javax.swing.JTextField();
        txt_fono_prov = new javax.swing.JTextField();
        txt_direc_prov = new javax.swing.JTextField();
        txt_desc_prov = new javax.swing.JTextField();
        lbl_cod_prov = new javax.swing.JLabel();
        lbl_cod_ciudad_prov = new javax.swing.JLabel();
        lbl_nom_prov = new javax.swing.JLabel();
        lbl_fono_prov = new javax.swing.JLabel();
        lbl_direc_prov = new javax.swing.JLabel();
        lbl_desc_prov = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_proveedores = new javax.swing.JTable();
        btn_limpiar = new javax.swing.JButton();
        cmb_proveedor = new javax.swing.JComboBox<>();
        txt_filtro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 800));
        setMinimumSize(new java.awt.Dimension(900, 800));
        setPreferredSize(new java.awt.Dimension(900, 800));

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 900));

        txt_cod_prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_provKeyTyped(evt);
            }
        });

        txt_cod_ciudad_prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cod_ciudad_provKeyTyped(evt);
            }
        });

        txt_nom_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nom_provActionPerformed(evt);
            }
        });
        txt_nom_prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nom_provKeyTyped(evt);
            }
        });

        txt_fono_prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_fono_provKeyTyped(evt);
            }
        });

        txt_direc_prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direc_provKeyTyped(evt);
            }
        });

        txt_desc_prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_desc_provKeyTyped(evt);
            }
        });

        lbl_cod_prov.setText("codigo del proveedor");

        lbl_cod_ciudad_prov.setText("codigo de la ciudad");

        lbl_nom_prov.setText("nombre del proveedor");

        lbl_fono_prov.setText("fono proveedor");

        lbl_direc_prov.setText("direccion del proveedor");

        lbl_desc_prov.setText("descripcion");

        btn_agregar.setText("agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        btn_consultar.setText("consultar");
        btn_consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarMouseClicked(evt);
            }
        });

        btn_modificar.setText("modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });

        btn_eliminar.setText("eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_volver.setText("volver");
        btn_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_volverMouseClicked(evt);
            }
        });

        tbl_proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_proveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_proveedores);

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limpiarMouseClicked(evt);
            }
        });

        cmb_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filtroKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_nom_prov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_fono_prov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_direc_prov, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                .addComponent(lbl_desc_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_cod_ciudad_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_cod_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(66, 66, 66)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_desc_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_direc_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_fono_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_nom_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_cod_ciudad_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_cod_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(btn_limpiar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(111, 111, 111)
                                    .addComponent(cmb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cod_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cod_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cod_ciudad_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cod_ciudad_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nom_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fono_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fono_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direc_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_direc_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_desc_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_desc_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_consultar)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btn_volver)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nom_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nom_provActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nom_provActionPerformed

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
         
        prov.setCod_prov(trim(txt_cod_prov.getText()));
        prov.setNom_prov(trim(txt_nom_prov.getText()));
        
    if  (trim(prov.getCod_prov()).equals("") || trim(prov.getNom_prov()).equals("")){
              JOptionPane.showMessageDialog(null, "indique codigo no se puede agregar un proveedor sin codigo o sin nombre");
              
          }else{
              if(JOptionPane.showConfirmDialog(null, "Desea agregar el proveedor de codigo  " + prov.getCod_prov(), "agregar proveedor",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {     
                      prov.setCod_ciudad(trim(txt_cod_ciudad_prov.getText()));
                      prov.setFono_prov(trim(txt_fono_prov.getText()));
                      prov.setDirec_prov(trim(txt_direc_prov.getText()));
                      prov.setDesc_prov(trim(txt_desc_prov.getText()));
                                qp.agregarproveedor(prov); 
                                    actualizar();
                                     Limpiar();
    }                                        
               Limpiar();
    
    }
        
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseClicked
        
        prov.setCod_prov(trim(txt_cod_prov.getText()));  
        
        if(prov.getCod_prov().equals("")){
              JOptionPane.showMessageDialog(null, "indique codigo no se puede consultar un proveedor sin codigo");
        }else{
       
        qp.consultarproveedor(prov);
       
        
         } 
    }//GEN-LAST:event_btn_consultarMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
 
       prov.setCod_prov(trim(txt_cod_prov.getText()));
        prov.setNom_prov(trim(txt_nom_prov.getText()));
        
    if  (trim(prov.getCod_prov()).equals("") || trim(prov.getNom_prov()).equals("")){
              JOptionPane.showMessageDialog(null, "indique codigo no se puede agregar un proveedor sin codigo o sin nombre");
              
          }else{
              if (JOptionPane.showConfirmDialog(null, "Desea modificar el proveedor con codigo  " + prov.getCod_prov(), "modificar proveedor",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {  
                      //validar si la ciudad del proveedor existe  
                  prov.setCod_ciudad(trim(txt_cod_ciudad_prov.getText()));
                  prov.setFono_prov(trim(txt_fono_prov.getText()));
                  prov.setDirec_prov(trim(txt_direc_prov.getText()));
                  prov.setDesc_prov(trim(txt_desc_prov.getText()));
                  
                    qp.modificarproveedor(prov); 
                    actualizar();
                    Limpiar();
                  }
           Limpiar(); 
          }        
        
        
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
  
                 prov.setCod_prov(trim(txt_cod_prov.getText()));
          if  (prov.getCod_prov().equals("")){
              JOptionPane.showMessageDialog(null, "Seleccione o indique codigo del proveedor a eliminar");
              
          }else{
              if (JOptionPane.showConfirmDialog(null, "Desea eliminar el proveedor de codigo  " + prov.getCod_prov(), "Eliminar proveedor",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {
                qp.eliminarproveedor(prov.getCod_prov());
                tbl_proveedores.removeAll();
                
                actualizar();
                Limpiar();
              }
               Limpiar();
          } 
        
        
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseClicked
        ven_principal vp = new ven_principal();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volverMouseClicked

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       
         prov.setCod_prov(trim(txt_cod_prov.getText()));  
         if (txt_cod_prov.getText().equals("")) {
                 System.out.println("ingrese un codigo a eliminar");
         } else{ 
        
          qp.eliminarproveedor(prov);
          tbl_proveedores.removeAll();
          actualizar();
       } 
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_cod_provKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_provKeyTyped
      vali.validarlargoalfa(evt, txt_cod_prov, 10);
    }//GEN-LAST:event_txt_cod_provKeyTyped

    private void tbl_proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_proveedoresMouseClicked
      
        txt_cod_prov.setText(tbl_proveedores.getModel().getValueAt(tbl_proveedores.getSelectedRow(), 0).toString());
        txt_cod_ciudad_prov.setText(tbl_proveedores.getModel().getValueAt(tbl_proveedores.getSelectedRow(), 1).toString());
        txt_nom_prov.setText(tbl_proveedores.getModel().getValueAt(tbl_proveedores.getSelectedRow(), 2).toString());
        txt_fono_prov.setText(tbl_proveedores.getModel().getValueAt(tbl_proveedores.getSelectedRow(), 3).toString());
        txt_direc_prov.setText(tbl_proveedores.getModel().getValueAt(tbl_proveedores.getSelectedRow(), 4).toString());
        txt_desc_prov.setText(tbl_proveedores.getModel().getValueAt(tbl_proveedores.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_tbl_proveedoresMouseClicked

    private void txt_cod_ciudad_provKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cod_ciudad_provKeyTyped
        vali.validarlargoalfa(evt, txt_cod_prov, 10);
        
    }//GEN-LAST:event_txt_cod_ciudad_provKeyTyped

    private void txt_nom_provKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nom_provKeyTyped
        vali.validarlargoalfa(evt, txt_cod_prov,30);
    }//GEN-LAST:event_txt_nom_provKeyTyped

    private void txt_fono_provKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fono_provKeyTyped
        vali.validarlargoalfa(evt, txt_cod_prov, 12);
    }//GEN-LAST:event_txt_fono_provKeyTyped

    private void txt_direc_provKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direc_provKeyTyped
       vali.validarlargoalfa(evt, txt_cod_prov, 30);
    }//GEN-LAST:event_txt_direc_provKeyTyped

    private void txt_desc_provKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_desc_provKeyTyped
        vali.validarlargoalfa(evt, txt_cod_prov,40);
    }//GEN-LAST:event_txt_desc_provKeyTyped

    private void btn_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limpiarMouseClicked
       Limpiar();
    }//GEN-LAST:event_btn_limpiarMouseClicked

    private void txt_filtroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtroKeyReleased
          String buscar = (String) cmb_proveedor.getSelectedItem();
       tbl_proveedores.setModel(qp.buscarDatos(txt_filtro.getText(), buscar));
    }//GEN-LAST:event_txt_filtroKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ven_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ven_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ven_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ven_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ven_proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cmb_proveedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cod_ciudad_prov;
    private javax.swing.JLabel lbl_cod_prov;
    private javax.swing.JLabel lbl_desc_prov;
    private javax.swing.JLabel lbl_direc_prov;
    private javax.swing.JLabel lbl_fono_prov;
    private javax.swing.JLabel lbl_nom_prov;
    private javax.swing.JTable tbl_proveedores;
    private javax.swing.JTextField txt_cod_ciudad_prov;
    private javax.swing.JTextField txt_cod_prov;
    private javax.swing.JTextField txt_desc_prov;
    private javax.swing.JTextField txt_direc_prov;
    private javax.swing.JTextField txt_filtro;
    private javax.swing.JTextField txt_fono_prov;
    private javax.swing.JTextField txt_nom_prov;
    // End of variables declaration//GEN-END:variables

public void Limpiar() {
        txt_cod_prov.setText("");
        txt_cod_ciudad_prov.setText("");
        txt_nom_prov.setText("");
        txt_fono_prov.setText("");
        txt_direc_prov.setText("");
        txt_desc_prov.setText("");
    }

       public void actualizar(){
         DefaultTableModel modelo = new DefaultTableModel();
         modelo=qp.cargardatos();
         tbl_proveedores.setModel(modelo);
         cmb_proveedor.setModel(cargarcmb_filtro());
    }
    
    // este metodo es para el filtro falta cambiar
      public DefaultComboBoxModel cargarcmb_filtro(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Codigo de proveedor");
        modelo.addElement("Codigo de ciudad");       
        modelo.addElement("Nombre de proveedor");
        modelo.addElement("Fono de proveedor");
        modelo.addElement("Direccion de proveedor");
        modelo.addElement("Descripcion");
        return modelo;
    }
    


}

