/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantasha;

import clases.Validar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Ivan
 */
public class ven_principal extends javax.swing.JFrame {

    /**
     * Creates new form ven_inicio
     */
    public ven_principal() {
        initComponents();
        this.setLocationRelativeTo(null);
             }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_manusu = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_manper = new javax.swing.JButton();
        btn_manpro = new javax.swing.JButton();
        btn_ajustes = new javax.swing.JButton();
        btn_proveedores = new javax.swing.JButton();
        btn_ciudad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jPanel2.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel2.setLayout(null);

        btn_manusu.setText("Mantenedor de usuarios");
        btn_manusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_manusuMouseClicked(evt);
            }
        });
        jPanel2.add(btn_manusu);
        btn_manusu.setBounds(190, 120, 210, 39);

        btn_exit.setText("Cerrar Sesion");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_exit);
        btn_exit.setBounds(460, 410, 105, 40);

        btn_manper.setText("Mantenedor de personas");
        btn_manper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_manperMouseClicked(evt);
            }
        });
        jPanel2.add(btn_manper);
        btn_manper.setBounds(190, 70, 210, 40);

        btn_manpro.setText("Mantenedor de productos");
        btn_manpro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_manproMouseClicked(evt);
            }
        });
        btn_manpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manproActionPerformed(evt);
            }
        });
        jPanel2.add(btn_manpro);
        btn_manpro.setBounds(190, 20, 210, 40);

        btn_ajustes.setText("Mantendor de ajustes(productos)");
        btn_ajustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ajustesMouseClicked(evt);
            }
        });
        jPanel2.add(btn_ajustes);
        btn_ajustes.setBounds(190, 180, 210, 40);

        btn_proveedores.setText("Mantenedor de proveedores");
        btn_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proveedoresMouseClicked(evt);
            }
        });
        jPanel2.add(btn_proveedores);
        btn_proveedores.setBounds(190, 240, 210, 40);

        btn_ciudad.setText("ciudad");
        btn_ciudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ciudadMouseClicked(evt);
            }
        });
        btn_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ciudadActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ciudad);
        btn_ciudad.setBounds(420, 330, 100, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 580, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_manproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manproActionPerformed
        
    }//GEN-LAST:event_btn_manproActionPerformed

    private void btn_manperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manperMouseClicked
        ven_cliente vper = new ven_cliente();
        vper.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_manperMouseClicked

    private void btn_manproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manproMouseClicked
        ven_prod vp = new ven_prod();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_manproMouseClicked

    private void btn_manusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manusuMouseClicked
        ven_usuario vu = new ven_usuario();
        vu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_manusuMouseClicked

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        inicio i = new inicio();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_ajustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajustesMouseClicked
        ven_ajuste ajuste =new ven_ajuste();
        ajuste.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ajustesMouseClicked

    private void btn_proveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedoresMouseClicked
        ven_proveedor proveedor = new ven_proveedor();
        proveedor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_proveedoresMouseClicked

    private void btn_ciudadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ciudadMouseClicked
       ven_ciudad ciudad = new ven_ciudad();
       ciudad.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_ciudadMouseClicked

    private void btn_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ciudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ven_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ven_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ven_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ven_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ven_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajustes;
    private javax.swing.JButton btn_ciudad;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_manper;
    private javax.swing.JButton btn_manpro;
    private javax.swing.JButton btn_manusu;
    private javax.swing.JButton btn_proveedores;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
