/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantasha;

import clases.venta;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import querys.Qprod_ventas;
import querys.Qventa;

/**
 *
 * @author Ariel
 */
public class ven_mantenedor_ventas extends javax.swing.JFrame {

    /**
     * Creates new form ven_mantenedor_ventas
     */
    Qventa qven = new Qventa();
    Qprod_ventas qproven = new Qprod_ventas();
    venta ven = new venta();

    public ven_mantenedor_ventas() {
        initComponents();
        this.setLocationRelativeTo(null);
        tbl_ventas.setModel(qven.cargardatos());
        cmb_filtro_ventas.setModel(cargarcmb_filtro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ventas = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        cmb_filtro_ventas = new javax.swing.JComboBox<>();
        txt_filtro_ventas = new javax.swing.JTextField();
        btn_consultar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_ventas);

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });

        cmb_filtro_ventas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_filtro_ventas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filtro_ventasKeyReleased(evt);
            }
        });

        btn_consultar.setText("Consultar");
        btn_consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarMouseClicked(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        btn_volver.setText("Volver");
        btn_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_volverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cmb_filtro_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(txt_filtro_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_volver)
                        .addGap(159, 159, 159))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_modificar)
                        .addGap(39, 39, 39)
                        .addComponent(btn_consultar)
                        .addGap(52, 52, 52)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_filtro_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_filtro_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregar)
                            .addComponent(btn_modificar)
                            .addComponent(btn_consultar)
                            .addComponent(btn_eliminar))
                        .addGap(192, 192, 192))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_volver)
                        .addGap(62, 62, 62))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_filtro_ventasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtro_ventasKeyReleased
        String buscar = (String) cmb_filtro_ventas.getSelectedItem();
        Qventa qven = new Qventa();
        tbl_ventas.setModel(qven.buscarDatos(txt_filtro_ventas.getText(), buscar));
    }//GEN-LAST:event_txt_filtro_ventasKeyReleased

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        ven_ventas vven = new ven_ventas();
        this.dispose();
        vven.setVisible(true);
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseClicked
        String id_venta = (String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 0);
        String abono = (String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 5);
        String saldo = (String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 6);
        String total = (String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 7);
        String num_boleta  = (String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 9);      
        ven.setId_venta(Integer.parseInt(id_venta));
        ven.setRut_cliente((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 1));
        ven.setId_usuario((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 2));
        ven.setFecha_rec((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 3));
        ven.setFecha_ent((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 4));
        ven.setAbono(Integer.parseInt(abono));
        ven.setSaldo(Integer.parseInt(saldo));
        ven.setTotal_vent(Integer.parseInt(total));
        ven.setTipo_pago((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 8));
        ven.setNum_boleta(Integer.parseInt(num_boleta));
        ven.setRut_pretiro((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 10));
        ven.setReceta((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 11));

        String consultar = "s";

          ven_ventas vven = new ven_ventas(ven,consultar);
        vven.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btn_consultarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        int index = tbl_ventas.getSelectedRow();
        String id_ventas = (String) tbl_ventas.getValueAt(index, 0);

        if (JOptionPane.showConfirmDialog(null, "Desea eliminar la venta  " + id_ventas, "Eliminar venta",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {
            qproven.eliminarProductoVenta(id_ventas);
            qven.eliminarVenta(id_ventas);
            tbl_ventas.removeAll();
            actualizar();
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
       
         String id_venta = (String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 0);
        String abono = (String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 5);
        String saldo = (String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 6);
        String total = (String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 7);
        String num_boleta  = (String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 9);      
        ven.setId_venta(Integer.parseInt(id_venta));
        ven.setRut_cliente((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 1));
        ven.setId_usuario((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 2));
        ven.setFecha_rec((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 3));
        ven.setFecha_ent((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 4));
        ven.setAbono(Integer.parseInt(abono));
        ven.setSaldo(Integer.parseInt(saldo));
        ven.setTotal_vent(Integer.parseInt(total));
        ven.setTipo_pago((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 8));
        ven.setNum_boleta(Integer.parseInt(num_boleta));
        ven.setRut_pretiro((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 10));
        ven.setReceta((String) tbl_ventas.getValueAt(tbl_ventas.getSelectedRow(), 11));

        String modificar = "s";
        System.out.println(ven.getId_venta()+ "id de boton modificar mantenedor");
          ven_ventas vven = new ven_ventas(modificar,ven);
        vven.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseClicked
     ven_principal vp = new ven_principal();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ven_mantenedor_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ven_mantenedor_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ven_mantenedor_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ven_mantenedor_ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ven_mantenedor_ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cmb_filtro_ventas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ventas;
    private javax.swing.JTextField txt_filtro_ventas;
    // End of variables declaration//GEN-END:variables

    public void actualizar() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = qven.cargardatos();
        tbl_ventas.setModel(modelo);
    }

    public DefaultComboBoxModel cargarcmb_filtro() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Id de venta");
        modelo.addElement("Rut de cliente");
        modelo.addElement("ID usuario");
        modelo.addElement("Fecha recibo");
        modelo.addElement("Fecha entrega");
        modelo.addElement("Abono");
        modelo.addElement("Saldo");
        modelo.addElement("Total");
        modelo.addElement("Tipo de pago");
        modelo.addElement("Numero de boleta");
        modelo.addElement("Rut persona que retira");
        modelo.addElement("Receta");

        return modelo;
    }

}
