/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantasha;

import clases.Persona;
import clases.Usuario;
import clases.Validar;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeString.trim;
import querys.Qpersona;
import querys.Qusuario;

/**
 *
 * @author Ivan
 * 
 * 
 * 
 * 
 */
public class ven_usuario extends javax.swing.JFrame {

    /**
     * Creates new form ven_agregaru
     * 
     * 
     *
     */
    
    
     Qusuario qusu = new Qusuario();
    
     Validar vali = new Validar(); 
     
    
    public ven_usuario() {
          initComponents();
        this.setLocationRelativeTo(null);
        tbl_usuario.setModel(qusu.cargardatos());
         cmb_usuario.setModel(cargarcmb_filtro());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_usu = new javax.swing.JTextField();
        txt_cargo = new javax.swing.JTextField();
        jp_pass = new javax.swing.JPasswordField();
        btn_volver = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_nom_usuario = new javax.swing.JTextField();
        btn_consultar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_usuario = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        cmb_usuario = new javax.swing.JComboBox<>();
        txt_filtro_usuario = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        jLabel1.setText("id_usuario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(32, 45, 137, 20);

        jLabel2.setText("password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 210, 137, 23);

        jLabel3.setText("cargo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 137, 26);

        txt_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuActionPerformed(evt);
            }
        });
        txt_usu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usuKeyTyped(evt);
            }
        });
        jPanel1.add(txt_usu);
        txt_usu.setBounds(170, 40, 170, 30);

        txt_cargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cargoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cargo);
        txt_cargo.setBounds(170, 90, 170, 30);

        jp_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jp_passKeyTyped(evt);
            }
        });
        jPanel1.add(jp_pass);
        jp_pass.setBounds(170, 200, 170, 30);

        btn_volver.setText("volver");
        btn_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_volverMouseClicked(evt);
            }
        });
        jPanel1.add(btn_volver);
        btn_volver.setBounds(440, 490, 70, 30);

        btn_eliminar.setText("eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar);
        btn_eliminar.setBounds(400, 310, 110, 30);

        jLabel5.setText("nombre usuario");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 160, 80, 14);

        txt_nom_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nom_usuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nom_usuario);
        txt_nom_usuario.setBounds(170, 150, 170, 30);

        btn_consultar.setText("consultar");
        btn_consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_consultar);
        btn_consultar.setBounds(180, 310, 90, 30);

        btn_modificar.setText("modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_modificar);
        btn_modificar.setBounds(290, 310, 90, 30);

        tbl_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usuarioMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_usuario);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(20, 360, 490, 110);

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_agregar);
        btn_agregar.setBounds(63, 310, 80, 30);

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limpiarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_limpiar);
        btn_limpiar.setBounds(410, 250, 100, 23);

        cmb_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmb_usuarioKeyReleased(evt);
            }
        });
        jPanel1.add(cmb_usuario);
        cmb_usuario.setBounds(370, 180, 70, 20);

        txt_filtro_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filtro_usuarioKeyReleased(evt);
            }
        });
        jPanel1.add(txt_filtro_usuario);
        txt_filtro_usuario.setBounds(459, 180, 90, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuActionPerformed

    private void btn_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseClicked
     ven_principal vp = new ven_principal();
       vp.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_volverMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        
<<<<<<< HEAD
           Usuario usu = new Usuario();
                 usu.setUsuario(trim(txt_usu.getText()));
          if  (usu.getUsuario().equals("")){
              JOptionPane.showMessageDialog(null, "Seleccione o indique codigo del usuario a eliminar");
              
          }else{
              if (JOptionPane.showConfirmDialog(null, "Desea eliminar el usuario  " + usu.getUsuario(), "Eliminar usuario",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {
                qusu.eliminarusuario(usu);
                tbl_usuario.removeAll();
                
                actualizar();
                Limpiar();
              }
               Limpiar();
          } 

        
        
        
        
=======
        Usuario usu = new Usuario();
        usu.setId_usuario(txt_usu.getText());
        Qusuario query = new Qusuario();   
        query.eliminarusuario(usu);
        JOptionPane.showMessageDialog(null,"eliminado con exito");
>>>>>>> 5aa465b18e0cfdddb6e0680e031d841b2c4839c2
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
         
        
       /* Usuario usu = new Usuario();
        usu.setUsuario(txt_usu.getText());
        usu.setNom_usuario(txt_nom_usuario.getText());
        usu.setPassword(String.valueOf(jp_pass.getPassword()));
        usu.setId_cargo(txt_cargo.getText());  
       */
       
        Usuario usu = new Usuario();
        usu.setId_usuario(trim(txt_usu.getText()));
           
        
<<<<<<< HEAD
         vali.validarRut(usu.getUsuario());
        if ( vali.validarRut(usu.getUsuario())== false){
              JOptionPane.showMessageDialog(null, "rut ingresado no valido");
        }
         
             
        else if (usu.getUsuario().length() < 10) {
             JOptionPane.showMessageDialog(null, "rut no valido, reingrese");
        } else {
              
            if (JOptionPane.showConfirmDialog(null, "Desea agregar el Usuario" + usu.getUsuario(), "agregar usuario",
=======
         if  (trim(usu.getId_usuario()).equals("") || trim(usu.getNom_usuario()).equals("")){
              JOptionPane.showMessageDialog(null, "indique codigo no se puede agregar un usuario sin codigo");
              
          }else{
           
        
              if                                  
                      (JOptionPane.showConfirmDialog(null, "Desea agregar el codigo  " + usu.getId_usuario(), "agregar usuario",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {     
                  
                   } else {
                  
                   if (JOptionPane.showConfirmDialog(null, "Desea agregar el usuario de Id  " + usu.getId_usuario(), "agregar usuario",
>>>>>>> 5aa465b18e0cfdddb6e0680e031d841b2c4839c2
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {

                usu.setNom_usuario(txt_nom_usuario.getText());
                usu.setId_cargo(txt_cargo.getText());
                usu.setPassword(String.valueOf(jp_pass.getPassword()));
                
                qusu.agregarusuario(usu);
                actualizar();
                Limpiar();
            }

            Limpiar();
        }
                   
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void txt_usuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuKeyTyped
        // TODO add your handling code here:
        vali.validarlargoalfa(evt, txt_usu,10);
    }//GEN-LAST:event_txt_usuKeyTyped

    private void txt_cargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cargoKeyTyped
        // TODO add your handling code here:
        vali.solonumerospositivos(evt);
        vali.validarlargonumerico(evt, txt_cargo,1);
    }//GEN-LAST:event_txt_cargoKeyTyped

    private void txt_nom_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nom_usuarioKeyTyped
        // TODO add your handling code here:
        vali.validarlargoalfa(evt, txt_nom_usuario,30);
    }//GEN-LAST:event_txt_nom_usuarioKeyTyped

    private void jp_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jp_passKeyTyped
        // TODO add your handling code here:
        vali.validarlargoalfa(evt, jp_pass,10);
    }//GEN-LAST:event_jp_passKeyTyped

    private void btn_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limpiarMouseClicked
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btn_limpiarMouseClicked

    private void btn_consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseClicked
        // TODO add your handling code here:
        
              Usuario usu = new Usuario();
        usu.setUsuario(trim(txt_usu.getText()));  
        
        if(usu.getUsuario().equals("")){
              JOptionPane.showMessageDialog(null, "indique usuario a consultar");
        }else{
       
        qusu.consultarusuario(usu);
         } 
    }//GEN-LAST:event_btn_consultarMouseClicked

    private void tbl_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usuarioMouseClicked
        // TODO add your handling code here:
        
        txt_usu.setText(tbl_usuario.getModel().getValueAt(tbl_usuario.getSelectedRow(), 0).toString());
        txt_nom_usuario.setText(tbl_usuario.getModel().getValueAt(tbl_usuario.getSelectedRow(), 1).toString());
        txt_cargo.setText(tbl_usuario.getModel().getValueAt(tbl_usuario.getSelectedRow(), 2).toString());
        jp_pass.setText(tbl_usuario.getModel().getValueAt(tbl_usuario.getSelectedRow(), 2).toString());
        
        
    }//GEN-LAST:event_tbl_usuarioMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        // TODO add your handling code here:
        
           Usuario usu = new Usuario();
   
             
        usu.setUsuario(trim(txt_usu.getText()));

        if (usu.getUsuario().equals("")) {
            JOptionPane.showMessageDialog(null, "indique usuario, no se puede modifcar sin usuario");

        } else {
            if (JOptionPane.showConfirmDialog(null, "Desea modificar el usuario con codigo  " + usu.getUsuario(), "modificar usuario",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {
                // PUEDE QUE SE TENGA QUE VALIDAR CUANDO EL FONO O LA DIR ES VACIA ASIGNAR NULL HAY QUE PROBAR
                usu.setNom_usuario(trim(txt_nom_usuario.getText()));
                usu.setId_cargo(trim(txt_cargo.getText()));
                usu.setPassword(String.valueOf(jp_pass.getPassword()));
                
                
                qusu.modificarusuario(usu);
                actualizar();
                Limpiar();
            }
            Limpiar();
        }
        
        
        
        
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void cmb_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_usuarioKeyReleased
        // TODO add your handling code here:
        
   
        
    }//GEN-LAST:event_cmb_usuarioKeyReleased

    private void txt_filtro_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtro_usuarioKeyReleased
        // TODO add your handling code here:
         String buscar = (String) cmb_usuario.getSelectedItem();
       Qusuario qusu = new  Qusuario();
       tbl_usuario.setModel(qusu.buscarDatos(txt_filtro_usuario.getText(), buscar));
        
        
    }//GEN-LAST:event_txt_filtro_usuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ven_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ven_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ven_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ven_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ven_usuario().setVisible(true);
            }
        });
    }

    
    
    
    
     public void Limpiar() {
         
        jp_pass.setText("");   
        txt_usu.setText("");
        txt_cargo.setText("");
        txt_nom_usuario.setText("");
        
    }

     
    public void actualizar() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = qusu.cargardatos();
        tbl_usuario.setModel(modelo);
    

       }
    

    
        public DefaultComboBoxModel cargarcmb_filtro(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Id de usuario");
        modelo.addElement("Cargo");       
        modelo.addElement("Nombre de usuario");
       
        return modelo;
    }
    
    
    
     
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cmb_usuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPasswordField jp_pass;
    private javax.swing.JTable tbl_usuario;
    private javax.swing.JTextField txt_cargo;
    private javax.swing.JTextField txt_filtro_usuario;
    private javax.swing.JTextField txt_nom_usuario;
    private javax.swing.JTextField txt_usu;
    // End of variables declaration//GEN-END:variables
}
