/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantasha;

import clases.OrdenPedido;
import clases.Proveedores;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import querys.Qpedidos;
import querys.Qproveedor;


public class ven_buscar_proveedor extends javax.swing.JFrame {
     ven_pedido ven = new ven_pedido();
     Qproveedor qp = new Qproveedor();
      Qpedidos qpedi = new Qpedidos();
      OrdenPedido odp = new OrdenPedido();
      String modificar;
      int sw;
     String text;
     int num_factura;
     String fecha_compra;
     int total;
    public ven_buscar_proveedor() {
        initComponents();
        tbl_proveedores.setModel(qp.cargardatos());
        cmb_proveedor.setModel(cargarcmb_filtroproveedor());
    }

    ven_buscar_proveedor(String text) {
       initComponents();
        tbl_proveedores.setModel(qp.cargardatos());
        cmb_proveedor.setModel(cargarcmb_filtroproveedor());
        this.text= text;
    }

    ven_buscar_proveedor( int sw) {
         initComponents();
         this.sw = sw;
        tbl_proveedores.setModel(qp.cargardatos());
        cmb_proveedor.setModel(cargarcmb_filtroproveedor());
        this.text= text;
    }

    ven_buscar_proveedor(int sw,int num_factura,String fecha_compra,int total ) {
     initComponents();
     this.sw = sw;
     this.num_factura = num_factura;
     this.fecha_compra = fecha_compra;
     this.total = total;
        tbl_proveedores.setModel(qp.cargardatos());
        cmb_proveedor.setModel(cargarcmb_filtroproveedor());
     
    }

    ven_buscar_proveedor(String modificar, OrdenPedido odp) {
       initComponents();
        tbl_proveedores.setModel(qp.cargardatos());
        cmb_proveedor.setModel(cargarcmb_filtroproveedor());
        this.modificar = modificar;
        this.odp = odp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_proveedores = new javax.swing.JTable();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        cmb_proveedor = new javax.swing.JComboBox<>();
        txt_filtro_proveedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_proveedores);

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aceptarMouseClicked(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        cmb_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_filtro_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filtro_proveedorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cancelar)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_filtro_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(97, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_filtro_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aceptarMouseClicked
    if(sw==1){
         Proveedores p = new Proveedores();
        int fila = tbl_proveedores.getSelectedRow();
        p.setCod_prov((String)tbl_proveedores.getValueAt(fila,0));
        p.setNom_prov((String)tbl_proveedores.getValueAt(fila,2));
        p.setFono_prov((String)tbl_proveedores.getValueAt(fila,3));
        this.dispose();
        ven_factura venf = new ven_factura(p);
        venf.setVisible(true);
    }else if(sw==2){
          Proveedores p = new Proveedores();
        int fila = tbl_proveedores.getSelectedRow();
        p.setCod_prov((String)tbl_proveedores.getValueAt(fila,0));
        p.setNom_prov((String)tbl_proveedores.getValueAt(fila,2));
        p.setFono_prov((String)tbl_proveedores.getValueAt(fila,3));
        this.dispose();
        ven_factura venf = new ven_factura(p,num_factura,fecha_compra,total);
        venf.setVisible(true);
    }else if(modificar.equals("s")){
          Proveedores p = new Proveedores();
        int fila = tbl_proveedores.getSelectedRow();
        p.setCod_prov((String)tbl_proveedores.getValueAt(fila,0));
        p.setNom_prov((String)tbl_proveedores.getValueAt(fila,2));
        p.setFono_prov((String)tbl_proveedores.getValueAt(fila,3));
        this.dispose();
          ven_pedido venp = new ven_pedido(modificar,odp,p);
        venp.setVisible(true);
        
    }else{
         Proveedores p = new Proveedores();
        int fila = tbl_proveedores.getSelectedRow();
        p.setCod_prov((String)tbl_proveedores.getValueAt(fila,0));
        p.setNom_prov((String)tbl_proveedores.getValueAt(fila,2));
        p.setFono_prov((String)tbl_proveedores.getValueAt(fila,3));
        this.dispose();
        ven_pedido venp = new ven_pedido(p,text);
        venp.setVisible(true);
    }   
       
    }//GEN-LAST:event_btn_aceptarMouseClicked

    private void txt_filtro_proveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtro_proveedorKeyReleased
        String buscar = (String) cmb_proveedor.getSelectedItem();
       tbl_proveedores.setModel(qp.buscarDatos(txt_filtro_proveedor.getText(), buscar));
    }//GEN-LAST:event_txt_filtro_proveedorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ven_buscar_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ven_buscar_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ven_buscar_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ven_buscar_proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ven_buscar_proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox<String> cmb_proveedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_proveedores;
    private javax.swing.JTextField txt_filtro_proveedor;
    // End of variables declaration//GEN-END:variables

  
      public DefaultComboBoxModel cargarcmb_filtroproveedor(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Codigo de proveedor");
        modelo.addElement("Codigo de ciudad");       
        modelo.addElement("Nombre de proveedor");
        modelo.addElement("Fono de proveedor");
        modelo.addElement("Direccion de proveedor");
        modelo.addElement("Descripcion");
        return modelo;
    }
    
    


}
