/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantasha;

import clases.FacturaCompra;
import clases.Proveedores;
import com.sun.xml.internal.messaging.saaj.packaging.mime.util.QDecoderStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import querys.QDetalleFacturaCompra;
import querys.QfacturaCompra;

/**
 *
 * @author Ariel
 */
public class ven_mantenedor_factura extends javax.swing.JFrame {

    QfacturaCompra qfc = new QfacturaCompra();
    QDetalleFacturaCompra qdfc = new QDetalleFacturaCompra();
    FacturaCompra fc = new FacturaCompra();

    public ven_mantenedor_factura() {
        initComponents();
        this.setLocationRelativeTo(null);
        tbl_factura_compra.setModel(qfc.cargardatos());
        cmb_factura_compra.setModel(cargarcmb_filtro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_factura_compra = new javax.swing.JTable();
        txt_filtro_factura_compra = new javax.swing.JTextField();
        cmb_factura_compra = new javax.swing.JComboBox<>();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(tbl_factura_compra);

        txt_filtro_factura_compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filtro_factura_compraKeyReleased(evt);
            }
        });

        cmb_factura_compra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        btn_consultar.setText("Consultar");
        btn_consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultarMouseClicked(evt);
            }
        });

        btn_volver.setText("Volver");
        btn_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_volverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btn_agregar)
                        .addGap(37, 37, 37)
                        .addComponent(btn_modificar)
                        .addGap(47, 47, 47)
                        .addComponent(btn_eliminar)
                        .addGap(51, 51, 51)
                        .addComponent(btn_consultar)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmb_factura_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_filtro_factura_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_volver))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filtro_factura_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_factura_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_consultar))
                .addGap(29, 29, 29)
                .addComponent(btn_volver))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_filtro_factura_compraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtro_factura_compraKeyReleased
        String buscar = (String) cmb_factura_compra.getSelectedItem();
        tbl_factura_compra.setModel(qfc.buscarDatos(txt_filtro_factura_compra.getText(), buscar));
    }//GEN-LAST:event_txt_filtro_factura_compraKeyReleased

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        ven_factura vf = new ven_factura();
        vf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        int num_factura = Integer.parseInt((String) tbl_factura_compra.getValueAt(tbl_factura_compra.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(null, "Desea eliminar el pedido  " + num_factura, "Eliminar pedido",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null) == JOptionPane.OK_OPTION) {
            qdfc.eliminarDetalleFacturaCompra(num_factura);
            qfc.eliminarFacturaCompra(num_factura);
            tbl_factura_compra.removeAll();
            actualizar();
        }


    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        String num_factura;
        String total;
        num_factura = (String) tbl_factura_compra.getValueAt(tbl_factura_compra.getSelectedRow(), 0);
        total = (String) tbl_factura_compra.getValueAt(tbl_factura_compra.getSelectedRow(), 3);

        fc.setNum_factura(Integer.parseInt(num_factura));
        fc.setCod_prov((String) tbl_factura_compra.getValueAt(tbl_factura_compra.getSelectedRow(), 1));
        fc.setFecha_compra((String) tbl_factura_compra.getValueAt(tbl_factura_compra.getSelectedRow(), 2));
        fc.setTotal(Integer.parseInt(total));

        ven_factura vf = new ven_factura(fc);
        vf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultarMouseClicked
        String num_factura;
        String total;
        num_factura = (String) tbl_factura_compra.getValueAt(tbl_factura_compra.getSelectedRow(), 0);
        total = (String) tbl_factura_compra.getValueAt(tbl_factura_compra.getSelectedRow(), 3);

        fc.setNum_factura(Integer.parseInt(num_factura));
        fc.setCod_prov((String) tbl_factura_compra.getValueAt(tbl_factura_compra.getSelectedRow(), 1));
        fc.setFecha_compra((String) tbl_factura_compra.getValueAt(tbl_factura_compra.getSelectedRow(), 2));
        fc.setTotal(Integer.parseInt(total));

        String consultar = "";

        ven_factura venf = new ven_factura(consultar, fc);
        venf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_consultarMouseClicked

    private void btn_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseClicked
     ven_principal vp = new ven_principal();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ven_mantenedor_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ven_mantenedor_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ven_mantenedor_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ven_mantenedor_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ven_mantenedor_factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cmb_factura_compra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_factura_compra;
    private javax.swing.JTextField txt_filtro_factura_compra;
    // End of variables declaration//GEN-END:variables

    public void actualizar() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = qfc.cargardatos();
        tbl_factura_compra.setModel(modelo);
    }

    public DefaultComboBoxModel cargarcmb_filtro() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Numero de Factura");
        modelo.addElement("Codigo de Proveedor");
        modelo.addElement("Fecha de Compra");
        modelo.addElement("Total");
        return modelo;
    }

}
